name: Automatic Production Pull
run-name: ${{ github.actor }} pushed to production.
on: [push]
jobs:
  production-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Remote Code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd /var/www/default && git pull --recurse-submodules
